# Generated by Django 5.1.6 on 2025-05-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('admin', 'Administrateur')], default='etudiant', max_length=20),
        ),
    ]
