# Generated by Django 5.1.6 on 2025-05-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_consultation_telechargement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telechargement',
            name='book',
        ),
        migrations.RemoveField(
            model_name='telechargement',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='Telechargement',
        ),
    ]
